
type EspecialidadMedica {
	id:				Int!
	nombre:			String!
	descripcion:	String!
}

type Query {
	especialidadesMedicas: [EspecialidadMedica!]! @authorized
	especialidadMedica(id: Int!): EspecialidadMedica! @authorized
}
