type Beneficiarios{
    codigo: String!
	ficha: Int!
	paterno: String
	materno: String
	nombre: String!
	parentesco: String!	
	sexo: String!
	gsanguineo: String!
	pertinencia: String!	
	ci: String!
	expedido: String!
	estamento: String!
	sindical: String!
	telefono: String!
}

type Query {
    # Sacar toda la lista de beneficiarios
	consultaBeneficiarios: [Beneficiarios!]! @authorized
    # Sacar solo un beneficiario 
	consultaBeneficiario(id: String!): Beneficiarios! @authorized
}
