
# Copyright (C) 2023, All Rights Reserved
# Written by Juan Carlos Labrandero <jcharly@labrandero.com>

type Role {
	id:				String!
	name:			String!
	descripcion:	String

	permissions:	[Permission!]!
}
