
# Copyright (C) 2023, All Rights Reserved
# Written by Juan Carlos Labrandero <jcharly@labrandero.com>

type User {
	id:				String!
	userName:		String!
	displayName:	String
	email:			String
	active:			Boolean

	roles: [Role!]!
}

type Auth {
	bearer:			String!
	authorization:	String!
}

input ISignInArgs {
	userName:	String!,
	password:	String!
}

input IUserCreateArgs {
	userName:			String!
	displayName:		String
	email:				String

	password:			String
	confirmPassword:	String
}


type Query {
	users: [User!]! @authorized
	currentUser(bearer: String!): User! @authorized
}

type Mutation {
	signIn(data: ISignInArgs!): Auth!
	signOut(bearer: String!): String! @authorized

	createUser(data: IUserCreateArgs!): User!
}

type Subscription {
	userCreated: User!
}
