

type SupplierSpecialtyType {
	id:		String!
	name:	String!
}

input ISupplierSpecialtyTypeArgs {
	name: String!
}


type Query {
	supplierSpecialtyTypes: [SupplierSpecialtyType!]! @authorized
	supplierSpecialtyType(id: String!): SupplierSpecialtyType! @authorized
}

type Mutation {
	createSupplierSpecialtyType(data: ISupplierSpecialtyTypeArgs!): SupplierSpecialtyType!
	updateSupplierSpecialtyType(id: String!, data: ISupplierSpecialtyTypeArgs!): SupplierSpecialtyType!
	deleteSupplierSpecialtyType(id: String!): SupplierSpecialtyType!
}
