

type SupplierServiceType {
	id:		String!
	name:	String!
}

input ISupplierServiceTypeArgs {
	name: String!
}


type Query {
	supplierServiceTypes: [SupplierServiceType!]! @authorized
	supplierServiceType(id: String!): SupplierServiceType! @authorized
}

type Mutation {
	createSupplierServiceType(data: ISupplierServiceTypeArgs!): SupplierServiceType!
}
