
type SupplierRelevance {
	id:	String!
	address: String!
	phone: String!

}

input ISupplierRelevanceArgs {
	
	addres: String!
	phone: String!
	supplierId:	String!
}

type Mutation {
	createSupplierRelevance(data: ISupplierRelevanceArgs!): SupplierRelevance!}


type Query {
	supplierRelevances: [SupplierRelevance!]! @authorized
	supplierRelevance(id: String!): SupplierRelevance! @authorized
}


