type ConsultaMedica{
    id:             String!
    #fecha:          DateTime
    #hora:           DateTime          
    valoracion:     String!
    examen_fisico:  String!
    diagnostico:    String!
    status:         Int!
    
    #medicamentos:   [Medicamento!]!
    #consultasexternas:   [ConsultaExterna!]!
    #incapacidades:       [Patient_Discharge!]!

}

input ConsultaMedicaArgs {
	valoracion:     String!
    examen_fisico:  String!
    diagnostico:    String!
    beneficiarioId:      String!
}

type Query {
    # Sacar toda la lista de consultas medicas
	consultaMedicas: [ConsultaMedica!]! @authorized
    # Sacar una consulta medica en especifico 
	consultaMedica(id: String!): ConsultaMedica! @authorized
}

type Mutation {
	createconsultaMedica(data: ConsultaMedicaArgs!): ConsultaMedica!
	updateconsultaMedica(id: String!, data: ConsultaMedicaArgs!): ConsultaMedica!
	deleteconsultaMedica(id: String!): ConsultaMedica!
}