
type ConsultaSignosVitales {
	id:						Int!
	temperaturaCorporal:	String
	frecuenciaCardiaca:		String
	frecuenciaRespiratoria:	String
	presionArterial:		String
	talla:					String
	peso:					String
}
