
type SupplierServiceType {
	id:		Int!
	name:	String!
}


input ICreateSupplierServiceType {
	name: String!
}

input IUpdateSupplierServiceType {
	name: String
}


type Query {
	supplierServiceTypes: [SupplierServiceType!]! @authorized
	supplierServiceType(id: Int!): SupplierServiceType! @authorized
}

type Mutation {
	createSupplierServiceType(data: ICreateSupplierServiceType!): SupplierServiceType! @authorized
	updateSupplierServiceType(id: Int!, data: IUpdateSupplierServiceType!): SupplierServiceType! @authorized
	deleteSupplierServiceType(id: Int!): SupplierServiceType! @authorized
}
